### ISSUE TITLE
Business Analyst

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/oportunitatisicariere#124]
{
    "id": "business-analyst",
    "title": "Business Analyst",
    "employer": "ASOCIATIA OPORTUNITATI SI CARIERE",
    "department": "IT Department",
    "location": "România",
    "jobType": "Telemunca",
    "experience": "Experienta 0-10 ani / Junior-Senior",
    "salary": "voluntar",
    "aboutEmployer": {
        "photo": "https://github.com/peviitor-ro/oportunitatisicariere/blob/main/assets/sebi-pic.png",
        "name": "Sebi",
        "title": "Președinte",
        "phone": "0741 025 447",
        "email": "aocpeviitor@gmail.com",
        "address": "Zimbor, nr. 215, jud. Salaj"
    },
    "generalInfo": [
        "Durata: nederminata",
        "Tipul de job: norma intreaga",
        "Experienta: junior-senior, 0-10 ani",
        "Locatia: 100% Remote"
    ],
    "offerings": [
        "Dezvoltare abilitati tehnice si de business",
        "Munca in echipa",
        "Influentarea directa a deciziilor de business",
        "Proiecte complexe si provocatoare",
        "Dezvoltare personala si profesionala",
        "Traininguri despre metodologiile de analiza",
        "Posibilitatea de afirmare profesionala",
        "Responsabilitate",
        "Ownership",
        "Posibilitatea de a contribui intr-un proiect OPEN SOURCE"
    ],
    "demands": [
        "Abilitatea de a intelege si defini problemele de business",
        "Experienta in crearea de solutii eficiente pentru problemele de business",
        "Bune abilitati de comunicare",
        "Persoana proactiva si orientata catre rezultate",
        "Atentia la detalii si gândirea critică"
    ],
    "responsabilities": [
        "Revizuirea și definirea problemelor de business",
        "Crearea de solutii eficiente pentru problemele de business",
        "Comunicarea cu diferitele departamente pentru a înțelege mai bine problemele și necesitățile acestora",
        "Prezentarea de rapoarte periodice cu privire la progresul realizat",
        "Identificarea și monitorizarea indicatorilor de performanță"
    ],
    "jobDescription": "Căutăm un Business Analyst care să identifice, înțeleagă și definească problemele de business în cadrul organizației noastre. Dacă aveți experiență relevantă și sunteți un gânditor analitic, așteptăm cu nerăbdare să vă alăturați echipei noastre!"
}

_Originally posted by @sebiboga in https://github.com/peviitor-ro/oportunitatisicariere/issues/97#issuecomment-2156154304_

**Comment by iBixee** [comment]
🚨 Data Exposure Alert

It looks like personal data (phone number) has been included in this issue and others across the repository. Although the email is public and belongs to the organisation, the phone number is personal and should not be exposed in GitHub issues.
Please review and remove any personal phone numbers to ensure GDPR compliance.

The issue is being reopened so the responsible maintainers can take appropriate action.
