### ISSUE TITLE
HR

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/oportunitatisicariere#129]
{
    "id": "hr",
    "title": "HR",
    "employer": "ASOCIATIA OPORTUNITATI SI CARIERE",
    "department": "Administrative Department",
    "location": "România",
    "jobType": "Telemunca",
    "experience": "Experienta 0-10 ani / Junior-Senior",
    "salary": "voluntar",
    "aboutEmployer": {
        "photo": "https://github.com/peviitor-ro/oportunitatisicariere/blob/main/assets/sebi-pic.png",
        "name": "Sebi",
        "title": "Președinte",
        "phone": "0741 025 447",
        "email": "aocpeviitor@gmail.com",
        "address": "Zimbor, nr. 215, jud. Salaj"
    },
    "generalInfo": [
        "Durata: nederminata",
        "Tipul de job: norma intreaga",
        "Experienta: junior-senior, 0-10 ani",
        "Locatia: 100% Remote"
    ],
    "offerings": [
        "Oportunitatea de a lucra intr-un mediu dinamic si de colaborare",
        "Dezvoltare abilitati de HR",
        "Munca in echipa",
        "Networking cu persoane cu acelasi interes",
        "Responsabilitate",
        "Ownership",
        "Posibilitatea de a contribui intr-un proiect OPEN SOURCE"
    ],
    "demands": [
        "Abilități puternice de organizare și prioritizare",
        "Bune abilitati  comunicare si interpersonale",
        "Capacitatea de a lua decizii etice și corecte",
        "Abilitatea de a dezvolta strategii de retentie si recrutare",
        "Orientat catre rezultate"
    ],
    "responsabilities": [
        "Recrutarea si selectia voluntarilor",
        "Dezvoltarea si implementarea strategiilor de HR",
        "Gestionarea proceselor de onboarding pentru voluntari noi",
        "Crearea și menținerea unui mediu de lucru pozitiv",
        "Asigurarea complianței cu legile și reglementările de resurse umane"
    ],
    "jobDescription": "Căutăm o persoană pentru rolul de HR pentru a se alătura echipei noastre. Această persoană se va ocupa de recrutarea, selectia voluntarilor, implementarea strategiilor de HR, gestionarea proceselor de onboarding pentru voluntarii noi. Dacă aveți experiență relevantă și sunteți pasionat de acest domeniu, așteptăm cu nerăbdare să vă alăturați echipei noastre!"
}

_Originally posted by @sebiboga in https://github.com/peviitor-ro/oportunitatisicariere/issues/97#issuecomment-2156154477_

**Comment by iBixee** [comment]
🚨 Data Exposure Alert

It looks like personal data (phone number) has been included in this issue and others across the repository. Although the email is public and belongs to the organisation, the phone number is personal and should not be exposed in GitHub issues.
Please review and remove any personal phone numbers to ensure GDPR compliance.

The issue is being reopened so the responsible maintainers can take appropriate action.
