### ISSUE TITLE
add more info about TEAM involved

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/oportunitatisicariere#151]
1st phase include only founders team but we also need the TEAM that is involved in developing this project.
let's decide together about TEAM section

![image](https://github.com/peviitor-ro/oportunitatisicariere/assets/41440889/82646304-c6c6-4e43-bfa0-3a37a82de6e2)

**Comment by sebiboga** [comment]
* Adriana Cionca
* Talida Ganciu
* Patricia Istrate
* Laurentiu Baluta
* Andrei Cojocaru
* Adelina Guliman
* Rares Irimus

**Comment by talidag** [comment]
https://github.com/peviitor-ro/oportunitatisicariere/pull/208
