### ISSUE TITLE
"X" appears when you refresh the page on mobile

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/oportunitatisicariere#186]
URL: https://oportunitatisicariere.ro/
Browser: Safari
Device: iPhone 13 PRO
OS: iOS

**STEPS TO REPRODUCE**:

1 .Open the URL in the browser
2. Refresh the page several times

**EXPECTED RESULTS**:
When you refresh the page, nothing should appear in the background.

**ACTUAL RESULTS**:
When you refresh the page, "X" appears on the top of the page on the right.

https://github.com/peviitor-ro/oportunitatisicariere/assets/23164347/d99e0194-9ea6-4ecd-8211-35675667a42f

**Comment by talidag** [comment]
Can you please check this again?

**Comment by Florin201092** [comment]
It's still the same problem.

**Comment by talidag** [comment]
Can you please check this again? Thanks! 😄

**Comment by Florin201092** [comment]
It works now. Thank you!
