### ISSUE TITLE
The titles from the job description are unnoticeably small and some sections have no diacritics - mobile

### ISSUE THREAD

**Issue by CameliaAM** [peviitor-ro/oportunitatisicariere#191]
**ENVIRONMENT**

URL: https://oportunitatisicariere.ro/
Browser: Chrome
OS: Android

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Go to "Cum poti ajuta" section
3. Click on any job

**EXPECTED RESULTS:**

The titles are visible and all sections are written with diacritics (where is the case).

**ACTUAL RESULTS:**

The titles are too small and the content of the "Alte informatii (optional)" and "Ce oferim" sections has no diacritics.
![ab0f9415-822d-49cb-8e34-62a3bdf5c275 (1)](https://github.com/peviitor-ro/oportunitatisicariere/assets/34051862/95d5831c-ba29-453c-a0e8-bca7dc69f431)

**Comment by talidag** [comment]
Hello. Can you please check this again?

**Comment by Florin201092** [comment]
Check the font for the email section: 

![email](https://github.com/user-attachments/assets/87a4b3d6-0015-4f03-a6b4-9e1cbebe008c)

**Comment by talidag** [comment]
@adriandoinea Please fix the responsiveness for the Job Details page overall.

**Comment by talidag** [comment]
Hello @CameliaAM  @Florin201092 . Can you please check this again? :)

**Comment by Florin201092** [comment]
![WhatsApp Image 2024-09-12 at 12 31 18_17da8044](https://github.com/user-attachments/assets/5f5e0e5e-51d0-4fb7-8cb8-5b092b956ec4)

FIXED!
