### ISSUE TITLE
Carousel cards cramming on smaller screen

### ISSUE THREAD

**Issue by AndreiBarari** [peviitor-ro/oportunitatisicariere#202]
Browser: Chrome
OS: Android

https://github.com/peviitor-ro/oportunitatisicariere/assets/93517234/4e72193c-1caf-41f4-a23b-84974dcaba41

Expected results: When the user inputs something in the search field, only the first card that matches the input should be displayed. The other cards matching the input should be accessible only through carousel navigation options, such as swiping or arrows.

Actual result: When the user inputs something in the search field, if there is only one result, the card is shrinking in width and not occupying the available space. If there are more than one results, the cards are shrinking and cramming into the available width.

**Comment by talidag** [comment]
@AndreiBarari can you please check this again, and close the issue if it was fixed? 

Also, thanks for pointing it out!
