### ISSUE TITLE
TEAM section to be extended with TESTING team

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/oportunitatisicariere#217]
@AdelinaGuliman as Head of Testing will provide the list with people involved in testing of our software products developed by ASOCIATIA OPORTUNITATI SI CARIERE

We need their name, link to their linkedin account, link to github account and discord account
We also need a photo for each, moment where they give approval for their personal data stated above to be published on our website

@talidag

**Comment by AdelinaGuliman** [comment]
1. Diana Dragoi: [GitHub](https://github.com/DeedeeDL), [Linkedin](https://ro.linkedin.com/in/diana-lavinia-dragoi), Discord: deedee_diana3
![IMG_6348](https://github.com/peviitor-ro/oportunitatisicariere/assets/137428958/5c2b854d-9a66-4c3f-b4c3-0a3d5c35a12c)

2. Florin Nistor: [GitHub](https://github.com/Florin201092), [Linkedin](https://www.linkedin.com/in/florin-nistor-b9a766252/),  Discord: florin201092
![1664789707980](https://github.com/peviitor-ro/oportunitatisicariere/assets/137428958/015dd924-b2e7-4014-966e-2d7472414ceb)

3. Beatrix Racasanu: [GitHub](https://github.com/iBixee), [Linkedin](https://www.linkedin.com/in/beatrix-racasanu-14507411b/), Discord: itsybixyspider (

4. Elena Instratescu:[GitHub](https://github.com/Elena1303996), [Linkedin](http://linkedin.com/in/elena-ramona-istratescu-680564299), Discord: elena130399 ( 
![IMG_9814](https://github.com/peviitor-ro/oportunitatisicariere/assets/137428958/528a2cfc-bae0-4854-a82b-528312a096c3)

5. Catalina Ion: [GitHub](https://github.com/Catalinay), [Linkedin](https://www.linkedin.com/in/catalina-ion-3b62a61a9/), Discord: catalina.i ( 
![368026195_1716297785509511_834255423574697549_n_1717094270560](https://github.com/peviitor-ro/oportunitatisicariere/assets/137428958/c85bb9b1-9cb7-4038-a1b2-1586d462f37e)

6. Ionut Pintilie: [GitHub](https://github.com/yonutzu), [Linkedin](https://www.linkedin.com/in/ionut-pintilie-qa-engineer/), Discord: ionut0678 
![IMG_20170526_162316](https://github.com/peviitor-ro/oportunitatisicariere/assets/137428958/fc9f19e7-3ebb-4d92-8945-db01eb4fb524)

7. Bogdan Dumitrache: [GitHub](https://github.com/bogi1492) [Linkedin](https://www.linkedin.com/in/dumitrache-bogdan-aa03b31a4/), Discord: bogi1492 
![IMG-20220903-WA0002](https://github.com/peviitor-ro/oportunitatisicariere/assets/137428958/0fc79df5-ac78-4577-b8ff-26e15a1d5a6b)

8. Melinte Camelia: [GitHub](https://github.com/CameliaAM) [Linkedin](https://www.linkedin.com/in/cameliaamelinte/), Discord: kamikaze4616 
![BSP_7113](https://github.com/peviitor-ro/oportunitatisicariere/assets/137428958/b8f93485-50b1-41e0-b967-0dd32e4b700e)

**Comment by AdelinaGuliman** [comment]
The list is not over. I will come with more additions

**Comment by talidag** [comment]
@AdelinaGuliman please check what we added so far. Can you close this issue and continue to add members for another issue?

**Comment by DeedeeDL** [comment]
12. Caterina Bocaniciu, github: cati2023, https://www.linkedin.com/in/caterina-bocaniciu-121033305, Discord: cati2023
![image](https://github.com/user-attachments/assets/67aa329e-461c-418b-91a7-ff6603dc5bff)



13. Silvia Podac, https://github.com/SilviaP27, [linkedin.com/in/silvia-podac-621391268](http://linkedin.com/in/silvia-podac-621391268), Id-ul de discord: silvia13ps

![image](https://github.com/user-attachments/assets/acea16ad-56c3-4b67-88b0-0c0ddc305984)

**Comment by DeedeeDL** [comment]
To be continued...

**Comment by AdelinaGuliman** [comment]
@talidag this issue remains open as @DeedeeDL has started filling in the list of testers that will appear on the Opportunities and Careers site

**Comment by DeedeeDL** [comment]
18. Lucian Lodin, https://github.com/LucianLCI, www.linkedin.com/in/lodin-lucian-30527a294, Discord: lcigaming

![image](https://github.com/user-attachments/assets/5b48559a-738c-451a-9fe5-bc6bacdf3f57)


19. Radu Lutu, https://github.com/RaduLutu, https://www.linkedin.com/in/radu-l-b37409252/, Discord: raduww

![image](https://github.com/user-attachments/assets/29a63523-6e69-44ac-a55d-85e63b99935e)

20. Andreea Plugaru, https://github.com/aplugaru,  https://www.linkedin.com/in/andreea-plugaru-1a496ba8, Discord: andreea_60587  ; poza nu are

21. Roxana Danalache, https://github.com/RoxanaDanalache, http://www.linkedin.com/in/roxana-danalache, Discord ID: 465862
![image](https://github.com/user-attachments/assets/24af95a7-6e77-40e7-a44f-1783d32b88e1)
