### ISSUE TITLE
The header it is not locked on the Jobs pages in mobile mode

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/oportunitatisicariere#221]
URL: https://oportunitatisicariere.ro/
Browser: Safari
Device: iPhone 13 PRO
OS: iOS

**STEPS TO REPRODUCE**:

1 .Open the URL in the browser
2. Scroll down and click "Detalii" from any job
3. Observe that the header it is not locked.

**EXPECTED RESULTS**:
The header should be locked on the top of the page.

**ACTUAL RESULTS**:
The header it is not locked on the top of the page.

https://github.com/peviitor-ro/oportunitatisicariere/assets/23164347/cdcbd45f-7600-4064-84d8-1ea4add62283

**Comment by talidag** [comment]
@Florin201092 can you please check this again?

**Comment by Florin201092** [comment]
FIXED!
