### ISSUE TITLE
The "Înapoi la locurile de muncă" button is missing from the Jobs pages in mobile mode

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/oportunitatisicariere#222]
URL: https://oportunitatisicariere.ro/
Browser: Safari
Device: iPhone 13 PRO
OS: iOS

**STEPS TO REPRODUCE**:

1 .Open the URL in the browser
2. Scroll down and click "Detalii" from any job
3. Observe that the "Înapoi la locurile de muncă" button is missing.

**EXPECTED RESULTS**:
The "Înapoi la locurile de muncă" button should be under the header on the left side.

**ACTUAL RESULTS**:
The "Înapoi la locurile de muncă" button is missing in mobile mode.

https://github.com/peviitor-ro/oportunitatisicariere/assets/23164347/cdcbd45f-7600-4064-84d8-1ea4add62283

**Comment by talidag** [comment]
@Florin201092 can you please check this again?

**Comment by Florin201092** [comment]
FIXED!
