### ISSUE TITLE
The text under the "Echipa" section is not properly aligned.

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/oportunitatisicariere#223]
URL: https://oportunitatisicariere.ro/
Browser: Chrome
Device: Latptop
OS: Windows 11 PRO

**STEPS TO REPRODUCE**:

1 .Open the URL in the browser
2. Scroll down under the "Echipa" section
3. Observe that the text is not properly aligned.

**EXPECTED RESULTS**:
The text should be properly aligned.

**ACTUAL RESULTS**:
The text is not  properly aligned.

<img width="928" alt="image" src="https://github.com/peviitor-ro/oportunitatisicariere/assets/23164347/93674f38-583e-4219-98df-6e56f8e233b7">

**Comment by talidag** [comment]
Can you please check this again? Also, can you specifiy the screen size?

**Comment by Florin201092** [comment]
FIXED

<img width="470" alt="image" src="https://github.com/user-attachments/assets/069ee1f4-0c3c-4408-8758-efa090bf2b2c">


<img width="341" alt="image" src="https://github.com/user-attachments/assets/003a42c4-c9a6-4538-9a12-57130f8009ef">
