### ISSUE TITLE
Check if the images from the "De ce să ajuți?" section are aligned properly

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/oportunitatisicariere#229]
**Description:** You must check if the images from the "De ce să ajuți?" section are aligned properly.
**Precondition:** The [website ](https://oportunitatisicariere.ro/)is up and running

**Comment by Florin201092** [comment]
**Step 1:** Check if the images from the "De ce să ajuți?" section are aligned properly.

**Expected result:** The images from the "De ce să ajuți?" section should be aligned properly .

**Comment by Florin201092** [comment]
**Step 2:** Check if the images from the "De ce să ajuți?" section are aligned properly on your phone.

**Expected result:** The images from the "De ce să ajuți?" section should be aligned properly on your phone.

**Comment by DeedeeDL** [comment]
All passed succesfully . Step 1 tested on Linux Ubuntu and Step 2 tested on IOS.
