### ISSUE TITLE
Check if all images with members from "Echipa" section are aligned properly

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/oportunitatisicariere#230]
**Description:** You must check if all images with members from "Echipa" section are aligned properly.
**Precondition:** The [website ](https://oportunitatisicariere.ro/)is up and running

**Comment by Florin201092** [comment]
**Step 1:** Scroll down to "Echipa" section.

**Expected result:** The "Echipa" section should be displayed.

**Comment by Florin201092** [comment]
**Step 2:** Check if all images with members from "Membrii fondatori" are aligned properly.

**Expected result:** All images with members from "Membrii fondatori" should be aligned properly .

**Comment by Florin201092** [comment]
**Step 3:** Check if all images with members from "Membrii principali" are aligned properly.

**Expected result:** All images with members from "Membrii principali" should be aligned properly .

**Comment by Florin201092** [comment]
**Step 4:** Check if all images with members from "Membrii principali" are aligned properly.

**Expected result:** All images with members from "Membrii principali" should be aligned properly .

**Comment by Florin201092** [comment]
**Step 5:** Check if all images with members from "Membrii principali" are aligned properly on your phone.

**Expected result:** All images with members from "Membrii principali" should be aligned properly on your phone.

**Comment by bogi1492** [comment]
**ENVIRONMENT**: Usability
URL: https://oportunitatisicariere.ro/
Browser: Chrome
Device: Mobile ( Motorola Edge 30)
OS: Android 13

**STEPS TO REPRODUCE**:

1 .Open the URL in the browser
2. Scroll down to ”Echipa” section
3. Check if all the images with ”Membrii principali” are aligned properly

**EXPECTED RESULTS**:
All the images are aligned properly with spacing as specified. No image is protruding out or pushed in.

**ACTUAL RESULTS**:
During the review, some images were found to be improperly aligned.

**ATTACHEMENTS:**



![Image](https://github.com/user-attachments/assets/545a2077-49f6-4108-b79d-3726ceaa2a8d)
![Image](https://github.com/user-attachments/assets/421cb5e6-15ed-44b7-8a0c-be2e469136b0)

**Comment by talidag** [comment]
This issue should be fixed now. Can you please check again? Thanks!

**Comment by Florin201092** [comment]
FIXED!
