### ISSUE TITLE
The Github account link asociated to Patricia Istrate is missing from the "Echipa" section

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/oportunitatisicariere#232]
URL: https://oportunitatisicariere.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11 PRO

**STEPS TO REPRODUCE**:

1 .Open the URL in the browser
2. Scroll down and click "Echipa" section.
3. Observe that the Github account link asociated to Patricia Istrate is missing.

**EXPECTED RESULTS**:
Patricia Istrate should have Github account on "Echipa" section.

**ACTUAL RESULTS**:
Patricia Istrate doesn't have Github account on "Echipa" section.

<img width="357" alt="image" src="https://github.com/peviitor-ro/oportunitatisicariere/assets/23164347/dca0a2d1-3244-49aa-89d6-b33f19a0771c">

**Comment by talidag** [comment]
Since Patricia is a UI/UX Expert, she doesn't have a Github account.
