### ISSUE TITLE
The website's job section pages are displayed well when zooming out

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/oportunitatisicariere#291]
**Description  :** When zoom  zoom out the pages from the job section, all the content is displayed well.
**Precondition** :  the website is up and runing (https://oportunitatisicariere.ro/index.html#)

**Comment by DeedeeDL** [comment]
**Step 1 :** With the website opened, at the default window size of 100%, go to the section "Cum poti ajuta tu"
**Expected result :** At this section, a carrousel with images and with jobs titles is displayed and under each title is a button "Detalii"

**Comment by DeedeeDL** [comment]
**Step 2 :** Open one of the jobs.
**Expected result :**  The page with the details of the job is displayed.

**Comment by DeedeeDL** [comment]
**Step 3 :** Decrease the zoom level to  and verify the Layout Integrity .
 **Expected results :**  Elements should resize appropriately without overlapping or becoming misaligned.

**Comment by DeedeeDL** [comment]
**Step 4 :**  For each level of the zoom verify also Text Readability.
**Expected results :** Text should remain within its container.

**Comment by DeedeeDL** [comment]
**Step 7 :** Repeat these steps for few jobs pages.
**Expected results :** Everything should be well displayed.

**Comment by DeedeeDL** [comment]
**Step 1 :** With the website opened, at the default window size of 100%, go to the section "Cum poti ajuta tu"
**Expected result :** At this section, a carrousel with images and with jobs titles is displayed and under each title is a button "Detalii"

**Comment by DeedeeDL** [comment]
**Step 2 :** Open one of the jobs.
**Expected result :**  The page with the details of the job is displayed.

**Comment by DeedeeDL** [comment]
**Step 3 :** Decrease the zoom level to 90%, 75%, 50%, and 25%. and verify the Layout Integrity .
 **Expected results :**  Elements should resize appropriately without overlapping or becoming misaligned.

**Comment by DeedeeDL** [comment]
Step 4 : For each level of the zoom verify also Text Readability.
Expected results : Text should remain within its container.

**Comment by DeedeeDL** [comment]
**Step 5 :** For each level of zoom verify also Images and Media.
**Expected results :**  images and graphics resize correctly without distortion or loss of quality.

**Comment by DeedeeDL** [comment]
**Step 6:**  For each level of zoom verify also Interactive Elements
**Expected results :** Buttons and links remain accessible and functional.

**Comment by LoredanaFranciuc** [comment]
Leptop
Windows 10
Tested on: Chrome, Edge, Modzilla
