### ISSUE TITLE
Navigation Links on Chrome (latest version) on Android.

### ISSUE THREAD

**Issue by Georgianaredenstein** [peviitor-ro/oportunitatisicariere#302]
Description: Verify the main navigation links on Chrome (latest version) on Android.

Preconditions: The website https://oportunitatisicariere.ro/ is live and accessible.

**Comment by Georgianaredenstein** [comment]
Step 1: Open Chrome on an Android device.

Expected Result: Each navigation link should lead to the correct page, and the page should load without any issues.

**Comment by Georgianaredenstein** [comment]
Step 2: Navigate to https://oportunitatisicariere.ro/

Expected Result: Each navigation link should lead to the correct page, and the page should load without any issues.

**Comment by Georgianaredenstein** [comment]
Step 3: Click on each main navigation link (e.g., [Misiunea noastră] [Cum poți ajuta tu?] [De ce să ajuți?] [Echipa]

Expected Result: Each navigation link should lead to the correct page, and the page should load without any issues.

**Comment by Georgianaredenstein** [comment]
Step 4:	Observe the page loads and functionality.

Expected Result: Each navigation link should lead to the correct page, and the page should load without any issues.

**Comment by dmariancatalin** [comment]
Step 3: Click on each main navigation link (e.g., Misiunea noastră, Cum poți ajuta tu?, De ce să ajuți?, Echipa)

Expected Result: Each navigation link should lead to the correct page, and the page should load without any issues.

When I click on main navigation link it takes me to their respective pages, but the page zooms in, and the menu button in the upper right corner is no longer visible.

![Image](https://github.com/user-attachments/assets/c853d588-b840-4026-92ad-18126a700d39)
