### ISSUE TITLE
Wrong redirection of the link "Inapoi la locurile de munca" from the jobs section

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/oportunitatisicariere#322]
ENVIRONMENT:
url: https://oportunitatisicariere.ro
browser: Chrome
operating system: windows 10
device: laptop Intel

STEPS TO REPRODUCE:

Open the URL
Click on the link "Cum poti ajuta ta"
Open one of the jobs from the carrousel, by clicking on the button "Detalii"
After opening the job, go to the link "Inapoi la locurile de munca"

EXPECTED RESULTS: The link "Inapoi la locurile de munca" should redirect to the section "Cum poti ajuta tu" where you can see all the jobs.
ACTUAL RESULTS: The link "Inapoi la locurile de munca" redirected to the begining of the homepage of the Association.

**Comment by talidag** [comment]
Fixed. Can you please check again?

**Comment by DeedeeDL** [comment]
Retested..passed
