### ISSUE TITLE
ENHANCEMENT - Adding on the homepage the calendar of the meetings plus something extra 

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/oportunitatisicariere#335]
On the homepage of the Oportunitati si cariere website it should be nice if could be add the calendar of the meetings, like here : https://dev.to/ale23yfm/peviitorto-pe-jitsi-mpe .
Besides, add also prima saptamana SPRINT RETROSPECTIVE si SPRINT REVIEW, SPRINT PLANNING and a doua saptamana BACKLOG REFINEMENT & BUG TRIAGE MEETING

**Comment by talidag** [comment]
I need to fix the mobile version for this!

**Comment by talidag** [comment]
@DeedeeDL Can you please check and close this issue?

**Comment by DeedeeDL** [comment]
@talidag  Also, I think they also need this : Programul pentru săptămâni
Prima săptămână
Sprint Retrospective
Sprint Review
Sprint Planning
A doua săptămână
Backlog Refinement
Bug Triage Meeting
We need to ask for further info

**Comment by DeedeeDL** [comment]
Problem fixed
