### ISSUE TITLE
The arrow button which goes up the page is not functional anymore.

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/oportunitatisicariere#348]
URL: https://oportunitatisicariere.ro/
Browser: Safari
Device: Laptop 
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Scroll down 
3. Click on the button with an upright arrow which should scroll up the page.

EXPECTED RESULTS:
When pressing the arrow button the page should scroll up.

ACTUAL RESULTS:
When pressing the arrow nothing happens. Is disfunctional.

![arrow](https://github.com/user-attachments/assets/25487a31-8df7-40eb-8df4-4dbaba31dbbd)

**Comment by talidag** [comment]
@DeedeeDL can you please check and close if the issue was fixed?

**Comment by DeedeeDL** [comment]
Retested. Passed.
