### ISSUE TITLE
Inconsistent paragraph width

### ISSUE THREAD

**Issue by AndreiBarari** [peviitor-ro/oportunitatisicariere#380]
There are a few sections in which the width of the paragraphs is not consistent.
The width of the paragraphs should be consistent throughout the website.

![Desktop Screenshot 2024 10 16 - 14 42 40 44](https://github.com/user-attachments/assets/0a7b2534-9208-4e06-a273-76d399d238cc)
![Desktop Screenshot 2024 10 16 - 14 36 12 57](https://github.com/user-attachments/assets/20a54cd3-0949-4f37-8f3e-9dcc0de6b052)
![Desktop Screenshot 2024 10 16 - 14 37 51 58](https://github.com/user-attachments/assets/8385471b-e290-4267-851a-6d3b83a97cb2)

**Comment by adriandoinea** [comment]
@AndreiBarari I made all the paragraphs consistent for the desktop, having a width of 860px (as we have for 'De ce sa ajuti' section). Should they have a consistent width on smaller screens as well?
