### ISSUE TITLE
Backend team for website

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/oportunitatisicariere#394]
@ale23yfm 
@alina712 
@sebiboga 
@lalalaurentiu 
@CalinCatuta 

Links for discord, github and linkedin
The picture you want displayed on the website
Team and title/position

**Comment by CalinCatuta** [comment]
Nu mai sunt colaborator activ.

**Comment by ale23yfm** [comment]
Also add
@Stardust0070
@AlexandruCoca99

**Comment by AndreiBarari** [comment]
@ale23yfm Please tell them to upload their info in this issue or, either you send them or have them send them to me on discord

**Comment by ale23yfm** [comment]
Alexandru Coca - Junior PHP Developer
github: https://github.com/AlexandruCoca99
linked-in: https://www.linkedin.com/in/gheorghe-alexandru-coca-a3516a214/
discord: https://discord.com/users/125541351700824064
![b7dd0e96-d76c-4da1-83ab-82c7bd628987](https://github.com/user-attachments/assets/33772710-b629-4b48-8e6f-70f776c85fb5)

**Comment by AdelinaMoroaca** [comment]
@AlexandruCoca99 ~ added
