### ISSUE TITLE
Add Data Quality members to the Team section

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/oportunitatisicariere#405]
@Florin201092  , @AndreiBarari ,@Cristian-Emil

Team: Data Quality / Data Quality Tester
Nume: Cristian-Emil Zidarescu
GitHub: https://github.com/Cristian-Emil
Linkedin: https://www.linkedin.com/in/cristian-emil-zidarescu-a463814b/
Discord: cristian_zidarescu (https://discord.com/channels/@cristian_zidarescu)
Poza:  ![Cristian-Emil Zidarescu](https://github.com/user-attachments/assets/58e00d01-9d94-435a-91ea-54981b10fc25)

**Comment by AndreiBarari** [comment]
There is an issue opened for this purpose 
https://github.com/peviitor-ro/oportunitatisicariere/issues/399

**Comment by Cristian-Emil** [comment]
Am completat acvolo inainte . Pt mai multa siguranta am trimis ei asta ca sa nu gresesc.
