### ISSUE TITLE
AOC - the navbar freezes when scrolling up

### ISSUE THREAD

**Issue by Luvnrj** [peviitor-ro/oportunitatisicariere#417]
URL: https://oportunitatisicariere.ro/
Browser: Mozilla
Device: Desktop,Windows 10 Home

STEPS TO REPRODUCE:

    S1. Open the URL https://oportunitatisicariere.ro/ with the Mozilla browser
    S2. Scroll down the page then scroll up.

   

EXPECTED RESULTS:
The navbar should scroll up without freezing .

ACTUAL RESULTS:
The navbar freezes on intro-container, when scrolling up .
![freeze-navbar-err](https://github.com/user-attachments/assets/460070f5-cf3d-4539-bf55-5ac313bf581d)

**Comment by AndreiBarari** [comment]
@Luvnrj 
A fix has been approved
Please check if it has been fixed or if the error persists

**Comment by AdelinaMoroaca** [comment]
@Luvnrj can you please check, issue seems solved
![image](https://github.com/user-attachments/assets/1f2c8b80-fdd1-4a02-b576-8144dd8c71c2)

**Comment by Luvnrj** [comment]
Tested => the bug is fixed!
