### ISSUE TITLE
"Misiunea noastra", "De ce sa ajuti" and "Intalniri" links don't redirect correspondinglu

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/oportunitatisicariere#443]
URL: https://oportunitatisicariere.ro/
Browser: Edge
Device: PC

STEPS TO REPRODUCE:

S1. Open the URL https://oportunitatisicariere.ro/ with Edge browser
S2. Click on the Misiunea noastra link from the navbar
S3. Click on De ce sa ajuti link  from the navbar
S4 Click on the Intalniri link from the navbar

EXPECTED RESULTS: 
All the links should redirect on the correct section. 

ACTUAL RESULTS:
The links don't redirect correctly.

![misiunea_noastra](https://github.com/user-attachments/assets/93b428e4-05c6-4ba2-ac40-9a9097acc422)

**Comment by AdelinaMoroaca** [comment]
The production was updated.
Can you please check @DeedeeDL  one more time and confirm if redirect links is working as expected?
thx
the expected results from frontend side are:
![image](https://github.com/user-attachments/assets/931632cb-3373-4a55-9299-7865a2d5de52)
![image](https://github.com/user-attachments/assets/e8865150-d704-4602-b1a6-0a42500fe669)
![image](https://github.com/user-attachments/assets/a62d5027-45f5-444f-acef-d7757b83f114)

**Comment by DeedeeDL** [comment]
Retested. Passed.
