### ISSUE TITLE
The text content for one member  is  irelevant.

### ISSUE THREAD

**Issue by catiboc** [peviitor-ro/oportunitatisicariere#462]
**Description:**
Verify that the text content for members  is correct, relevant, and complete. One member has an irelevant text when his linkedin page is accessed.

Precondition: The page  https://oportunitatisicariere.ro/ is up and runing
Browser: Chrome
OS: Window11

>**Step 1**
Click on the "Echipa" section.

**Expected results:**
The "Echipa" section opens.

>**Step2**
Verify that the text content for members and founder is correct, relevant, and complete.

**Expected results.**
The text content for members and founder is correct, relevant, and complete.

**Actual result.**
If you click on Lucian Lodin's Linkedin icon from QA group, a wrong page is opening.

**Comment by AdelinaMoroaca** [comment]
This bug was fixed.
@catiboc can you check again?

**Comment by catiboc** [comment]
I have the same result.
![image](https://github.com/user-attachments/assets/f4a51929-a964-4fde-8bc9-7ef45c41e538)

**Comment by AdelinaMoroaca** [comment]
This is how the production was updated from the begining.

https://github.com/user-attachments/assets/432f210e-81f9-4c18-b374-9fd2ec1e34b0
