### ISSUE TITLE
"Echipa" link doesn't redirect correctly UI

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/oportunitatisicariere#464]
URL: https://oportunitatisicariere.ro/
Browser: Chrome
Device: Laptop
Operating system: Windows 11

**STEPS TO REPRODUCE**:

1. Open the URL https://oportunitatisicariere.ro/ with Chrome browser.
2. Click on the "Echipa" link from the navbar.

**EXPECTED RESULTS**: 
The link should redirect to the correct section. 

**ACTUAL RESULTS**:
The link doesn't redirect correctly.

![image](https://github.com/user-attachments/assets/c62d5439-b374-4da2-a96a-2a3bc2d5c8a5)

**Comment by AdelinaMoroaca** [comment]
fix will be on https://github.com/peviitor-ro/oportunitatisicariere/pull/497

**Comment by Lore78** [comment]
The "Echipa" title is cut out, it should have a top margin.

![image](https://github.com/user-attachments/assets/871b2f73-ef95-4d96-b78a-5c55b024c6a0)

**Comment by Lore78** [comment]
Awesome fixing! Thank you :)
