### ISSUE TITLE
[Icon's title misspelled] From 'De ce sa ajuti?' section a title from one category is misspelled

### ISSUE THREAD

**Issue by Alexandra9621** [peviitor-ro/oportunitatisicariere#475]
URL: [ASOCIAȚIA OPORTUNITĂȚI ȘI CARIERE](https://oportunitatisicariere.ro/) 
Browser: Chrome
Device: Laptop
Operating system: Windows

Steps to reproduce:

1. Scroll down to 'De ce sa ajuti?' section
2. Check all titles under each icon

Expected Result: The category title should be 'Experienta practica'
Actual result: The category title is "Exprienta practica'
![Mispelling bug](https://github.com/user-attachments/assets/afd467cc-386b-4881-b2a6-f7731231c734)

**Comment by AdelinaMoroaca** [comment]
@CarmenSteliana the issue was fixed, can you check again please ?
![image](https://github.com/user-attachments/assets/43fd745c-eb93-4233-87ee-f547cacc844f)

**Comment by Alexandra9621** [comment]
Checked. Fixed
