### ISSUE TITLE
Missing a space between two sentences  in the description of the "Event Planner" job.

### ISSUE THREAD

**Issue by LoredanaFranciuc** [peviitor-ro/oportunitatisicariere#483]
At the description section of the job "Event Planner" , between the second and the last sentence after the dot, there is no space.

![a space is missing](https://github.com/user-attachments/assets/0f67dbe2-44e3-4a42-abb4-e86bb845aa30)

**Comment by AdelinaMoroaca** [comment]
Hi @LoredanaFranciuc ,
The issue was fixed, can you please check again? thx

![image](https://github.com/user-attachments/assets/ae507cc4-f28b-4961-9cd0-bb0d2232dd12)

**Comment by LoredanaFranciuc** [comment]
I checked again. It's fixed. Thank you!
