### ISSUE TITLE
new testimonial for Adriana Cionca

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/oportunitatisicariere#498]
@AdrianaCionca please add here the TEXT and the image.

here is an example:

![image](https://github.com/user-attachments/assets/a2608688-948d-41a3-8520-69faadc0adc7)

**Comment by AdelinaMoroaca** [comment]
În cadrul Asociației Oportunități și Cariere am avut privilegiul de a face parte dintr-o echipă unită și dedicată. După 9 luni de muncă și învățare continuă în cadrul proiectului, am reușit să mă angajez în domeniu; 
Sentimentul de apartenență față de acest proiect m-au motivat să rămân implicată în continuare, ajutând noii colegi să se integreze și să se dezvolte așa cum am făcut și eu. ~ 66 cuvinte


Am avut privilegiul de a face parte dintr -o echipă unită și dedicată . După 9 luni de muncă și învățare continuă în cadrul proiectului , am reușit să mă angajez în domeniu ; 
Sentimentul de apartenență față de acest proiect m -au motivat să rămân implicată în continuare , ajutând noii colegi să se integreze și să se dezvolte așa cum am făcut și eu . ~ 60 cuv

**Comment by AdelinaMoroaca** [comment]
![image](https://github.com/user-attachments/assets/c3341b06-a7b5-41c5-9f78-452aa8b2b4ce)
