### ISSUE TITLE
add 45seconds delay between automatic change slider in "povesti de success" section

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/oportunitatisicariere#510]
we need at least 45seconds wait time before showing next slide in "povesti de success" section
user need time to:
  * read entire text
  * look at the picture
  * see the "povesti de success" title text
  * analize the slider functionality and design
  * see the role of the person 
  * spot the right dots where he can take actions with mouse
  * enjoy the UX experience

**Comment by AdelinaMoroaca** [comment]
issue was fixed @sebiboga
