### ISSUE TITLE
why the "povesti de success" section is before team section?

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/oportunitatisicariere#511]
I remember we talked about placing "povesti de success" section under "de ce sa ajuti?"
now, we can see this section "povesti de success" after "echipa"

**Comment by AdelinaMoroaca** [comment]
@sebiboga here you have the Figma layout; 
 https://www.figma.com/design/1fvOj1ECStKxx8VPenYX0u/Oportunitati-si-Cariere?node-id=0-1&node-type=canvas&t=D1mWrtSqtzqLMMNf-0 
 
 do you think we should move `povesti de succes` section after `de ce sa ajuti?`
