### ISSUE TITLE
The title “Voluntari” is misaligned 

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/oportunitatisicariere#516]
URL: https://oportunitatisicariere.ro/
Browser:  Chrome
Device: IPhone pro 13
OS: iOS

Steps to Reproduce:

Open the URL.
Go to the "Echipa" section
Verify the graphics and their titles.
Observe the alignment of the titles.

Actual Results
The title “Voluntari” is misaligned compared to the graphic.

Expected Results
All the titles are well alligned

![IMG_8650](https://github.com/user-attachments/assets/909fac90-5fbd-4370-82f3-5b245064fc67)
![IMG_8649](https://github.com/user-attachments/assets/55727319-b9ab-4627-960d-860d2efb018c)

**Comment by AdelinaMoroaca** [comment]
Hi @DeedeeDL , the issue was fixed, can you please check if everything works well now?
Thank you 
CC: @porobertdev

**Comment by porobertdev** [comment]
> Hi @DeedeeDL , the issue was fixed, can you please check if everything works well now? Thank you CC: @porobertdev

@DeedeeDL So I suppose everything is fine?

**Comment by AdelinaMoroaca** [comment]
@DeedeeDL from frontend perspective the bug was fixed.
Can you please re-test it?
Thank you

**Comment by DeedeeDL** [comment]
retested. passed. good job !
