### ISSUE TITLE
show/not show the open position

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/oportunitatisicariere#520]
@AndreiBarari  we need to extend data.json to have on option to show/not_show in front-end the open position
the reason NOT TO DELETE but to keep it hidden is that we want temporary to hide some of the jobs
not to rewrite the entire job_description, it's better to have this option to hide the opportunities where we already have enough people in our teams

Can we extend the data.json with a new key and this key to tell to the front-end when to hide and when to show it in the carousel? 
When hidden, somehow we should not have the possibility to read the job description even if we have the URL somewhere saved like for example: https://oportunitatisicariere.ro/details.html?id=devops-github should not be visible if we decide to hide it from the list.

![image](https://github.com/user-attachments/assets/c3846ab3-d9ba-4221-8ffe-fe800ca9b2ca)

**Comment by AndreiBarari** [comment]
@sebiboga It is doable, I will get on it.
